# Generated by Django 6.0 on 2025-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securityType', models.CharField(max_length=10)),
                ('instrumentToken', models.CharField(max_length=10)),
                ('exchangeSegment', models.CharField(max_length=10)),
            ],
        ),
    ]
