# Generated by Django 6.0 on 2025-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeId', models.CharField(max_length=100)),
                ('isShortSell', models.BooleanField(default=False)),
                ('openAt', models.DateTimeField(blank=True, null=True)),
                ('closeAt', models.DateTimeField(blank=True, null=True)),
                ('entryPrice', models.FloatField(blank=True, null=True)),
                ('exitPrice', models.FloatField(blank=True, null=True)),
                ('securityType', models.CharField(max_length=50)),
                ('instrumentToken', models.CharField(max_length=50)),
                ('exchangeSegment', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurationId', models.CharField(max_length=100)),
                ('iTokens', models.JSONField(default=list)),
                ('debounceTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeId', models.CharField(max_length=100)),
                ('isShortSell', models.BooleanField(default=False)),
                ('openAt', models.DateTimeField(blank=True, null=True)),
                ('closeAt', models.DateTimeField(blank=True, null=True)),
                ('entryPrice', models.FloatField(blank=True, null=True)),
                ('exitPrice', models.FloatField(blank=True, null=True)),
                ('securityType', models.CharField(max_length=50)),
                ('instrumentToken', models.CharField(max_length=50)),
                ('exchangeSegment', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeId', models.CharField(max_length=100)),
                ('isShortSell', models.BooleanField(default=False)),
                ('openAt', models.DateTimeField(blank=True, null=True)),
                ('closeAt', models.DateTimeField(blank=True, null=True)),
                ('entryPrice', models.FloatField(blank=True, null=True)),
                ('exitPrice', models.FloatField(blank=True, null=True)),
                ('securityType', models.CharField(max_length=50)),
                ('instrumentToken', models.CharField(max_length=50)),
                ('exchangeSegment', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
