# Generated by Django 6.0 on 2025-12-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_closeorder_configuration_currentorder_pendingorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='configurationId',
        ),
    ]
