# Generated by Django 6.0 on 2025-12-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_configuration_configurationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeorder',
            name='exitReason',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('WAITING', 'WAITING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='closeorder',
            name='strategyCode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('WAITING', 'WAITING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='stopLoss',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='strategyCode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentorder',
            name='target',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('WAITING', 'WAITING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='strategyCode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='triggerPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='closeAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='entryPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='exchangeSegment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='exitPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='instrumentToken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='openAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='securityType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='closeorder',
            name='tradeId',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='closeAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='entryPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='exchangeSegment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='exitPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='instrumentToken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='openAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='securityType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentorder',
            name='tradeId',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='closeAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='entryPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='exchangeSegment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='exitPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='instrumentToken',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='openAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='securityType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='tradeId',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
