import time
from utils.kotak_neo_api_main_v2.neo_api_client import NeoAPI
from utils.constant import USER_ID,CONSUMER_KEY, CONSUMER_SECRET, TOKEN, MOBILE, UCC, MPIN, TOTP, ENVIRONMENT, MCX_GOLD_TOKEN


# --- 1. Configuration (Replace with your actual details) --- 
CONSUMER_SECRET = TOKEN


# Note: The Scrip Token for Reliance Industries on NSE (NSE_EQ) changes 
# and must be fetched from the Scrip Master API or documented list.
# The value below is an example. You MUST get the current token.
RELIANCE_NSE_TOKEN = "11729"  # Example token for RELIANCE (NSE) 

# --- 2. Initialize and Authenticate ---
try:
    # 2.1. Initialize the NeoAPI client (FIXED: removed consumer_secret from __init__)
    client = NeoAPI(
        environment='prod',
        consumer_key=CONSUMER_KEY,  # Pass consumer_key here
        neo_fin_key=None,
        access_token=None
    )

    print("--- NeoAPI Client Initialized ---")
    
    # 2.2. Login and get the TOTP value
    # TOTP (Time-based One-Time Password) is generated by your authenticator app (e.g., Google Authenticator)
    totp_value = input(458346) 
    
    # The totp_login method uses the consumer_secret internally
    login_response = client.totp_login(USER_ID, MPIN, totp_value, CONSUMER_SECRET)
    
    if login_response.get('status') == 'success':
        print("Login Successful!")
        # The client object is now configured internally with the session tokens.
    else:
        print("Login Failed:", login_response)
        exit()

    # --- 3. Fetch Live Quotes for Reliance (RELIANCE.NS) ---

    # The quotes API expects a list of dictionaries with exchange segment and instrument token
    scrip_list = [
        {"exchange_segment": "NSE_EQ", "instrument_token": RELIANCE_NSE_TOKEN}
    ]

    print("\n--- Fetching live price for Reliance ---")
    
    # The quotes method retrieves the live data
    quotes_response = client.quotes(scrip_list=scrip_list)

    # --- 4. Process and Display the Live Price ---
    if quotes_response and quotes_response.get('status') == 'success' and quotes_response.get('data'):
        # Check if the list of quotes is not empty
        if quotes_response['data']:
            reliance_data = quotes_response['data'][0]
            
            # Use .get() for safe access to dictionary keys
            live_price = reliance_data.get('last_traded_price')
            
            print("-" * 40)
            print(f"Stock: {reliance_data.get('trading_symbol', 'N/A')}")
            print(f"Exchange: {reliance_data.get('exchange_segment', 'N/A')}")
            print(f"Instrument Token: {reliance_data.get('instrument_token', 'N/A')}")
            print(f"**Live Price (LTP): ₹{live_price}**")
            print(f"Time: {reliance_data.get('last_traded_time', 'N/A')}")
            print("-" * 40)
        else:
             print("Quotes API returned success, but the data list is empty.")
    else:
        print("\n--- Error during Quotes API call ---")
        print(f"Response: {json.dumps(quotes_response, indent=2)}")
        print("Possible Reasons: Incorrect Instrument Token or expired session.")

except Exception as e:
    print(f"An error occurred: {e}")

#